added support for storing the start and end address of a trip to be p…
CappyStone/CapybaraServer pull request #93
Opened 2022-10-18 20:40 UTC by skylathadani

added two more parameters to the trip, start and end address. hoping we can propagate these values over to the front end so users can see additional trip details

2022-10-18 20:44 UTC, Sn0wCh1ld requested changes
Looks like you commented out the environment vars that we'll need on prod. Also, could we change "start address" and "end address" to "startAddress" and "endAddress" respectively? Other than that looks good

2022-10-18 20:45 UTC, Sn0wCh1ld commented
Also, I can definitely add those to the front end once I'm done with this week's tests

2022-10-18 20:46 UTC, skylathadani commented
Sounds good! totally forgot about the commented out variables, good catch!

2022-10-19 21:09 UTC, Sn0wCh1ld approved these changes

2022-10-21 13:13 UTC, merged